package br.com.softlandsistemas.conhecimento.model.entity;
// Generated 01/11/2011 21:54:20 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Clientes generated by hbm2java
 */
public class Clientes  implements java.io.Serializable {


     private String codCli;
     private String razao;
     private String endCli;
     private String baiCli;
     private String cidCli;
     private String estCli;
     private String cepCli;
     private String cgcCli;
     private String contato;
     private String fonCli;
     private String rgCli;
     private Date dtNasc;
     private String endCob;
     private String baiCob;
     private String cidCob;
     private String estCob;
     private String cepCob;
     private String endEnt;
     private String baiEnt;
     private String cidEnt;
     private String estEnt;
     private String cepEnt;
     private String cpfCli;
     private String fonCli2;
     private String fax;
     private String pessoa;
     private String campo;
     private String email;
     private String emailContato;
     private String site;
     private Short ramo;
     private String nomefan;
     private Integer minuto;
     private Character particular;
     private String ipe;
     private String hora;
     private Character tipo;
     private Integer maquina;
     private Character rede;
     private String situafin;
     private String produto;
     private Date vigencia;
     private Date expiracao;
     private byte[] historico;
     private byte[] pendencia;
     private Date udata;
     private Integer situacao;
     private String personalizacao;
     private String documentacao;
     private String liberou;
     private Date dtRelease;
     private String userRelease;
     private String versaoBd;

    public Clientes() {
    }

	
    public Clientes(String codCli, String razao) {
        this.codCli = codCli;
        this.razao = razao;
    }
    public Clientes(String codCli, String razao, String endCli, String baiCli, String cidCli, String estCli, String cepCli, String cgcCli, String contato, String fonCli, String rgCli, Date dtNasc, String endCob, String baiCob, String cidCob, String estCob, String cepCob, String endEnt, String baiEnt, String cidEnt, String estEnt, String cepEnt, String cpfCli, String fonCli2, String fax, String pessoa, String campo, String email, String emailContato, String site, Short ramo, String nomefan, Integer minuto, Character particular, String ipe, String hora, Character tipo, Integer maquina, Character rede, String situafin, String produto, Date vigencia, Date expiracao, byte[] historico, byte[] pendencia, Date udata, Integer situacao, String personalizacao, String documentacao, String liberou, Date dtRelease, String userRelease, String versaoBd) {
       this.codCli = codCli;
       this.razao = razao;
       this.endCli = endCli;
       this.baiCli = baiCli;
       this.cidCli = cidCli;
       this.estCli = estCli;
       this.cepCli = cepCli;
       this.cgcCli = cgcCli;
       this.contato = contato;
       this.fonCli = fonCli;
       this.rgCli = rgCli;
       this.dtNasc = dtNasc;
       this.endCob = endCob;
       this.baiCob = baiCob;
       this.cidCob = cidCob;
       this.estCob = estCob;
       this.cepCob = cepCob;
       this.endEnt = endEnt;
       this.baiEnt = baiEnt;
       this.cidEnt = cidEnt;
       this.estEnt = estEnt;
       this.cepEnt = cepEnt;
       this.cpfCli = cpfCli;
       this.fonCli2 = fonCli2;
       this.fax = fax;
       this.pessoa = pessoa;
       this.campo = campo;
       this.email = email;
       this.emailContato = emailContato;
       this.site = site;
       this.ramo = ramo;
       this.nomefan = nomefan;
       this.minuto = minuto;
       this.particular = particular;
       this.ipe = ipe;
       this.hora = hora;
       this.tipo = tipo;
       this.maquina = maquina;
       this.rede = rede;
       this.situafin = situafin;
       this.produto = produto;
       this.vigencia = vigencia;
       this.expiracao = expiracao;
       this.historico = historico;
       this.pendencia = pendencia;
       this.udata = udata;
       this.situacao = situacao;
       this.personalizacao = personalizacao;
       this.documentacao = documentacao;
       this.liberou = liberou;
       this.dtRelease = dtRelease;
       this.userRelease = userRelease;
       this.versaoBd = versaoBd;
    }
   
    public String getCodCli() {
        return this.codCli;
    }
    
    public void setCodCli(String codCli) {
        this.codCli = codCli;
    }
    public String getRazao() {
        return this.razao;
    }
    
    public void setRazao(String razao) {
        this.razao = razao;
    }
    public String getEndCli() {
        return this.endCli;
    }
    
    public void setEndCli(String endCli) {
        this.endCli = endCli;
    }
    public String getBaiCli() {
        return this.baiCli;
    }
    
    public void setBaiCli(String baiCli) {
        this.baiCli = baiCli;
    }
    public String getCidCli() {
        return this.cidCli;
    }
    
    public void setCidCli(String cidCli) {
        this.cidCli = cidCli;
    }
    public String getEstCli() {
        return this.estCli;
    }
    
    public void setEstCli(String estCli) {
        this.estCli = estCli;
    }
    public String getCepCli() {
        return this.cepCli;
    }
    
    public void setCepCli(String cepCli) {
        this.cepCli = cepCli;
    }
    public String getCgcCli() {
        return this.cgcCli;
    }
    
    public void setCgcCli(String cgcCli) {
        this.cgcCli = cgcCli;
    }
    public String getContato() {
        return this.contato;
    }
    
    public void setContato(String contato) {
        this.contato = contato;
    }
    public String getFonCli() {
        return this.fonCli;
    }
    
    public void setFonCli(String fonCli) {
        this.fonCli = fonCli;
    }
    public String getRgCli() {
        return this.rgCli;
    }
    
    public void setRgCli(String rgCli) {
        this.rgCli = rgCli;
    }
    public Date getDtNasc() {
        return this.dtNasc;
    }
    
    public void setDtNasc(Date dtNasc) {
        this.dtNasc = dtNasc;
    }
    public String getEndCob() {
        return this.endCob;
    }
    
    public void setEndCob(String endCob) {
        this.endCob = endCob;
    }
    public String getBaiCob() {
        return this.baiCob;
    }
    
    public void setBaiCob(String baiCob) {
        this.baiCob = baiCob;
    }
    public String getCidCob() {
        return this.cidCob;
    }
    
    public void setCidCob(String cidCob) {
        this.cidCob = cidCob;
    }
    public String getEstCob() {
        return this.estCob;
    }
    
    public void setEstCob(String estCob) {
        this.estCob = estCob;
    }
    public String getCepCob() {
        return this.cepCob;
    }
    
    public void setCepCob(String cepCob) {
        this.cepCob = cepCob;
    }
    public String getEndEnt() {
        return this.endEnt;
    }
    
    public void setEndEnt(String endEnt) {
        this.endEnt = endEnt;
    }
    public String getBaiEnt() {
        return this.baiEnt;
    }
    
    public void setBaiEnt(String baiEnt) {
        this.baiEnt = baiEnt;
    }
    public String getCidEnt() {
        return this.cidEnt;
    }
    
    public void setCidEnt(String cidEnt) {
        this.cidEnt = cidEnt;
    }
    public String getEstEnt() {
        return this.estEnt;
    }
    
    public void setEstEnt(String estEnt) {
        this.estEnt = estEnt;
    }
    public String getCepEnt() {
        return this.cepEnt;
    }
    
    public void setCepEnt(String cepEnt) {
        this.cepEnt = cepEnt;
    }
    public String getCpfCli() {
        return this.cpfCli;
    }
    
    public void setCpfCli(String cpfCli) {
        this.cpfCli = cpfCli;
    }
    public String getFonCli2() {
        return this.fonCli2;
    }
    
    public void setFonCli2(String fonCli2) {
        this.fonCli2 = fonCli2;
    }
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
    public String getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(String pessoa) {
        this.pessoa = pessoa;
    }
    public String getCampo() {
        return this.campo;
    }
    
    public void setCampo(String campo) {
        this.campo = campo;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getEmailContato() {
        return this.emailContato;
    }
    
    public void setEmailContato(String emailContato) {
        this.emailContato = emailContato;
    }
    public String getSite() {
        return this.site;
    }
    
    public void setSite(String site) {
        this.site = site;
    }
    public Short getRamo() {
        return this.ramo;
    }
    
    public void setRamo(Short ramo) {
        this.ramo = ramo;
    }
    public String getNomefan() {
        return this.nomefan;
    }
    
    public void setNomefan(String nomefan) {
        this.nomefan = nomefan;
    }
    public Integer getMinuto() {
        return this.minuto;
    }
    
    public void setMinuto(Integer minuto) {
        this.minuto = minuto;
    }
    public Character getParticular() {
        return this.particular;
    }
    
    public void setParticular(Character particular) {
        this.particular = particular;
    }
    public String getIpe() {
        return this.ipe;
    }
    
    public void setIpe(String ipe) {
        this.ipe = ipe;
    }
    public String getHora() {
        return this.hora;
    }
    
    public void setHora(String hora) {
        this.hora = hora;
    }
    public Character getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Character tipo) {
        this.tipo = tipo;
    }
    public Integer getMaquina() {
        return this.maquina;
    }
    
    public void setMaquina(Integer maquina) {
        this.maquina = maquina;
    }
    public Character getRede() {
        return this.rede;
    }
    
    public void setRede(Character rede) {
        this.rede = rede;
    }
    public String getSituafin() {
        return this.situafin;
    }
    
    public void setSituafin(String situafin) {
        this.situafin = situafin;
    }
    public String getProduto() {
        return this.produto;
    }
    
    public void setProduto(String produto) {
        this.produto = produto;
    }
    public Date getVigencia() {
        return this.vigencia;
    }
    
    public void setVigencia(Date vigencia) {
        this.vigencia = vigencia;
    }
    public Date getExpiracao() {
        return this.expiracao;
    }
    
    public void setExpiracao(Date expiracao) {
        this.expiracao = expiracao;
    }
    public byte[] getHistorico() {
        return this.historico;
    }
    
    public void setHistorico(byte[] historico) {
        this.historico = historico;
    }
    public byte[] getPendencia() {
        return this.pendencia;
    }
    
    public void setPendencia(byte[] pendencia) {
        this.pendencia = pendencia;
    }
    public Date getUdata() {
        return this.udata;
    }
    
    public void setUdata(Date udata) {
        this.udata = udata;
    }
    public Integer getSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(Integer situacao) {
        this.situacao = situacao;
    }
    public String getPersonalizacao() {
        return this.personalizacao;
    }
    
    public void setPersonalizacao(String personalizacao) {
        this.personalizacao = personalizacao;
    }
    public String getDocumentacao() {
        return this.documentacao;
    }
    
    public void setDocumentacao(String documentacao) {
        this.documentacao = documentacao;
    }
    public String getLiberou() {
        return this.liberou;
    }
    
    public void setLiberou(String liberou) {
        this.liberou = liberou;
    }
    public Date getDtRelease() {
        return this.dtRelease;
    }
    
    public void setDtRelease(Date dtRelease) {
        this.dtRelease = dtRelease;
    }
    public String getUserRelease() {
        return this.userRelease;
    }
    
    public void setUserRelease(String userRelease) {
        this.userRelease = userRelease;
    }
    public String getVersaoBd() {
        return this.versaoBd;
    }
    
    public void setVersaoBd(String versaoBd) {
        this.versaoBd = versaoBd;
    }




}


