package br.com.softlandsistemas.conhecimento.model.entity;
// Generated 01/11/2011 21:54:20 by Hibernate Tools 3.2.1.GA



/**
 * Visita generated by hbm2java
 */
public class Visita  implements java.io.Serializable {


     private String codigo;
     private String descricao;

    public Visita() {
    }

	
    public Visita(String codigo) {
        this.codigo = codigo;
    }
    public Visita(String codigo, String descricao) {
       this.codigo = codigo;
       this.descricao = descricao;
    }
   
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }




}


